### ISSUE TITLE
Error in education_settings field in bedrock protocol schema

### ISSUE THREAD

**Issue by extremeheat** [PrismarineJS/minecraft-data#750]
https://github.com/PrismarineJS/minecraft-data/blob/1c5fb1f2517386b546c77b43e7f164943a338efa/data/bedrock/latest/proto.yml#L2885-L2887
should be 

```yaml
   external_link_settings: has_external_link_settings ?
     if true:
       has: bool
       url: string
       display_name: string
```

currently external_link_settings has empty switch fields
